export enum TokenType {
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACE, RIGHT_BRACE,
  COMMA, DOT, SEMICOLON, BACKSLASH,
  MINUS, PLUS, STAR, SLASH,
  BANG,
  EQUAL,
  GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, UNEQUAL,

  IDENTIFIER, STRING, NUMBER,
  TRUE, FALSE, NULL,

  PRINT, APPEND, REPLACE,
  LET, SET, DIM,
  AND, OR,

  IF, THEN, ELSE,
  FOR, TO, STEP, NEXT,
  WHILE, WEND,
  DEF, RETURN, DEND,

  INPUT,

  NEWLINE,
  EOF,
}
